version: '3.8'
services:
    web:
        container_name: php-apache
        build:
            context: ./docker/development/
            dockerfile: apache.dockerfile
        depends_on:
            - db
        volumes:
            - ./www:/app/
        ports:
            - 80:80
        restart: always
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
